export const MEDITATION_CATEGORY_DETAILS_UI = [
  {
    id: 'vipassana',
    name: 'විපස්සනා',
    nameEn: 'Vipassana',
    description: 'Insight meditation for wisdom',
    color: 'violet',
    icon: '⦿',
  },
  {
    id: 'samatha',
    name: 'සමත',
    nameEn: 'Samatha',
    description: 'Calm abiding and concentration',
    color: 'blue',
    icon: '◦',
  },
  {
    id: 'kasina',
    name: 'කසින',
    nameEn: 'Kasina',
    description: 'Focus on meditation objects',
    color: 'amber',
    icon: '◎',
  },
  {
    id: 'dasa-anussati',
    name: 'දස අනුස්සති',
    nameEn: 'Dasa Anussati',
    description: 'Ten Recollections',
    color: 'emerald',
    icon: '✦',
  },
  {
    id: 'dasa-asubha',
    name: 'දස අසුභ',
    nameEn: 'Dasa Asubha',
    description: 'Ten Impurities',
    color: 'slate',
    icon: '☠',
  },
  {
    id: 'brahma-vihara',
    name: 'සතර බ්‍රහ්ම විහරණ',
    nameEn: 'Satara Brahma Viharana',
    description: 'Four Divine Abodes',
    color: 'rose',
    icon: '❤',
  },
  {
    id: 'arupya',
    name: 'සතර ආරුප්‍ය',
    nameEn: 'Satara Arupya',
    description: 'Four Formless Jhanas',
    color: 'indigo',
    icon: '∞',
  },
  {
    id: 'dhatu-vavatthana',
    name: 'චතු ධාතු වවත්ථාන',
    nameEn: 'Chatu Dhatu Vavatthana',
    description: 'Four Element Analysis',
    color: 'cyan',
    icon: '🜃',
  },
  {
    id: 'ahara-patikkula',
    name: 'ආහාරයේ පටික්කූල සංඥාව',
    nameEn: 'Ahara Patikkula Sañña',
    description: 'Loathsomeness of Food',
    color: 'orange',
    icon: '🍽',
  },
  {
    id: 'nama-rupa-pariccheda',
    name: 'නාම රූප පරිච්ඡේද ඤාණය',
    nameEn: 'Nama Rupa Pariccheda Ñana',
    description: 'Mind-Matter Discrimination Knowledge',
    color: 'purple',
    icon: '⚛',
  },
  {
    id: 'paccaya-pariggaha',
    name: 'ප්‍රත්‍ය පරිග්‍රහ ඤාණය',
    nameEn: 'Paccaya Pariggaha Ñana',
    description: 'Comprehension of Conditions',
    color: 'teal',
    icon: '🔗',
  },
  {
    id: 'sammasana',
    name: 'සම්මස්සන ඤාණය',
    nameEn: 'Sammasana Ñana',
    description: 'Knowledge by Comprehension',
    color: 'lime',
    icon: '⊕',
  },
  {
    id: 'udayabbaya',
    name: 'උදයවය ඤාණය',
    nameEn: 'Udayabbaya Ñana',
    description: 'Rise and Fall Knowledge',
    color: 'sky',
    icon: '↕',
  },
  {
    id: 'bhanga',
    name: 'භංග ඤාණය',
    nameEn: 'Bhanga Ñana',
    description: 'Dissolution Knowledge',
    color: 'gray',
    icon: '⌛',
  },
  {
    id: 'bhaya',
    name: 'භයතුපට්ඨාන ඤාණය',
    nameEn: 'Bhaya Ñana',
    description: 'Fear Knowledge',
    color: 'red',
    icon: '⚠',
  },
  {
    id: 'adinava',
    name: 'ආදීනව ඤාණය',
    nameEn: 'Adinava Ñana',
    description: 'Danger Knowledge',
    color: 'yellow',
    icon: '⚡',
  },
  {
    id: 'nibbida',
    name: 'නිබ්බිදා ඤාණය',
    nameEn: 'Nibbida Ñana',
    description: 'Disenchantment Knowledge',
    color: 'stone',
    icon: '⊗',
  },
  {
    id: 'muncitukamyata',
    name: 'මුඤචිතුකම්‍යතා ඤාණය',
    nameEn: 'Muñcitukamyatā Ñana',
    description: 'Desire for Deliverance',
    color: 'zinc',
    icon: '🕊',
  },
  {
    id: 'patisankhanupassana',
    name: 'පටිසංඛානුසපස්සනා ඤාණය',
    nameEn: 'Paṭisaṅkhānupassanā Ñana',
    description: 'Re-observation Knowledge',
    color: 'neutral',
    icon: '🔄',
  },
  {
    id: 'sankharupekha',
    name: 'සංඛාරුපෙක්ඛා ඤාණය',
    nameEn: 'Saṅkhārupekkhā Ñana',
    description: 'Equanimity Towards Formations',
    color: 'blue-gray',
    icon: '⚖',
  },
  {
    id: 'anuloma',
    name: 'අනුලෝම ඤාණය',
    nameEn: 'Anuloma Ñana',
    description: 'Adaptation Knowledge',
    color: 'violet',
    icon: '➜',
  },
  {
    id: 'gotrabhu',
    name: 'ගෝත්‍රභූ ඤාණය',
    nameEn: 'Gotrabhū Ñana',
    description: 'Change of Lineage',
    color: 'fuchsia',
    icon: '⟳',
  },
  {
    id: 'magga',
    name: 'මාර්ග ඤාණය',
    nameEn: 'Magga Ñana',
    description: 'Path Knowledge',
    color: 'gold',
    icon: '✨',
  },
  {
    id: 'phala',
    name: 'ඵල ඤාණය',
    nameEn: 'Phala Ñana',
    description: 'Fruition Knowledge',
    color: 'amber',
    icon: '🏵',
  },
  {
    id: 'paccavekkhana',
    name: 'පච්චවෙක්ඛණ ඤාණය',
    nameEn: 'Paccavekkhaṇa Ñana',
    description: 'Reviewing Knowledge',
    color: 'emerald',
    icon: '👁',
  },
  {
    id: 'mindfulness',
    name: 'Mindfulness',
    nameEn: 'Mindfulness',
    description: 'Sati practice in daily life',
    color: 'green',
    icon: '☵',
  },
] as const;
